version: '3.7'

services:

  personal_website:
    container_name: deepanshululla.com
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: always
